#!/bin/bash

gnome-terminal -e "$1 ./app/$2/producer.$3 ./scenarios/round-robin/producer-1.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/round-robin/consumer-1.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/round-robin/consumer-2.json"
