#!/bin/bash

gnome-terminal -e "$1 ./app/$2/producer.$3 ./scenarios/default-to-default/producer-1.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/default-to-default/consumer-1.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/default-to-default/consumer-2.json"
