#!/bin/bash

gnome-terminal -e "$1 ./app/$2/producer.$3 ./scenarios/topic/producer-1.json"
gnome-terminal -e "$1 ./app/$2/producer.$3 ./scenarios/topic/producer-2.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/topic/consumer-1.json"
gnome-terminal -e "$1 ./app/$2/consumer.$3 ./scenarios/topic/consumer-2.json"
